### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by MostHated** [Tyrrrz/Contextual#1]
Hey there,
    I came across this yesterday, it looks quite useful. I am working on a small application (a Discord.Net bot) in which I was going to offer a few choices of database backend (LiteDB, SQLite, MySQL, etc). At the same moment I was trying to determine how I would like to go about being able pass around the database context of whichever one was chosen by the user, I came across this. From the looks of it, unless I am mistaken, this should be pretty ideal for something like that?

Thanks,
-MH

**Comment by Tyrrrz** [comment]
Hi @MostHated!
First of all, I'm surprised you already found it, given that I created this repo like yesterday and haven't told anyone yet 😂 
It's still an experimental project and it might have some design issues, but it should work for what you are describing.
I'd be really curious how it goes, so let me know :)

**Comment by MostHated** [comment]
Lol, I get that a lot. I like to spend time looking through all the new things that come out, trying things out, seeing if there is anything new I can learn from them, etc. 

Sure, I will play around with it and see how it works out and let you know if I come across anything and how it turns out. 👍

**Comment by Tyrrrz** [comment]
Thanks! I'm really curious because I haven't used this on a real project yet.
