### ISSUE TITLE
A number of issues :)

### ISSUE THREAD

**Issue by alexyakunin** [Tyrrrz/Contextual#2]
Hi @Tyrrrz , I've raised a few issues in this thread: https://twitter.com/alexyakunin/status/1335885438284832775

Use of `Stack<T>` is definitely a bug - you can verify this by adding a concurrent test; as for anything else, maybe it makes more sense to write about the pattern right on the first page of this repository - yes, lots of people don't know how to use this and when.

**Comment by Tyrrrz** [comment]
Hi @alexyakunin!

Thanks for pointing out these issues.

> 1) You can't use Stack<T> as underlying storage. ExecutionContext uses copy-on-write for a whole dictionary of its locals, which means their values can be shared across multiple async tasks, i.e. non-concurrent Stack version won't work.

I was thinking about this myself, but couldn't come up with a test that exercises this behavior (admittedly, I'm also bad at visualizing race conditions). There is one test for async, but it doesn't detect this issue: https://github.com/Tyrrrz/Contextual/blob/56ec22363f4cfa8756f87bc06f8afee3fd850e54/Contextual.Tests/MainSpecs.cs#L110-L146

> 2) Using a static member in generic type (Container<T>.Stack) every time you need a context will definitely hurt performance.

This one is surprising, I always thought it was a rather efficient way to implement a type-safe `Dictionary<Type, T>`. Do you think the performance loss may be offset by the overhead of AsyncLocal anyway?

> 3) Two prev. points mean that probably the most efficient way to do this is to implement an IDisposable that temporarily "swaps" an AsyncLocal value on creation & sets it back on disposal.

That's actually not a bad idea. That way we don't need the stack at all.

> But this means you don't need a lib for this - you'll implement it with nearly the same amount of code with Contextful or w/o it, esp. assuming Context.Use<T> is going to be more expensive in comparison to the one you can create.

Yeah, that's okay, the library is more of an example of a "correct" and tested implementation. I expect that if somebody wants to implement this pattern, they may just copy-paste the code anyway.

**Comment by alexyakunin** [comment]
On test - high chance you won't see a concurrency issue on this one, because you run just two ops concurrently. Run more - much more :) Besides that, use Task.Run - the pre-await part of your async tasks runs synchronously, so the order is always stable too.

**Comment by alexyakunin** [comment]
I would create a short "torture test" first here - e.g. create N async threads drilling M levels deep with context each. Read - UseOneLess - Read - etc.

**Comment by alexyakunin** [comment]
As for the static field in generic type, yes, it's basically a dictionary lookup - one extra to a couple of similar lookups you get with AsyncLocal, so you are expected to lose maybe 20-30% speed by doing this.

**Comment by alexyakunin** [comment]
Oh, and you can return struct instead of IDisposable in Provide to avoid boxing.

**Comment by alexyakunin** [comment]
Hi, on test - I mean something like this: https://github.com/servicetitan/Stl.Fusion/blob/master/tests/Stl.Tests/Async/AsyncLockTestBase.cs#L119

**Comment by alexyakunin** [comment]
And as for your change, one other thing to take into account is: you know the first part of any async task (pre-await) always runs as part of the calling task. And AFAIK `ExecutionContext` is associated with the caller's task while it runs. This means that if you start using a context there, it will likely "spill" to the caller. I am not absolutely sure this will happen, but this seems to be the right guess, so maybe adding a test to prove / disprove this makes sense too. Not much can be done to address this, of course - except taking this into acc.

**Comment by Tyrrrz** [comment]
> Hi, on test - I mean something like this:

Cool, thanks!

>  This means that if you start using a context there, it will likely "spill" to the caller. 

I'm not sure I understand this. Can you show some example code?

Also, do you think `Context.Provide`/`Context.Use` should be synchronized? In my (shallow) understanding, the same `AsyncLocal` instance won't be shared by two simultaneously executing threads, but I may be wrong.

**Comment by alexyakunin** [comment]
Hi @Tyrrrz , sorry, just got back to this.

> This means that if you start using a context there, it will likely "spill" to the caller.

Here is what I'm worried of:
- TaskA calls TaskB w/ "await TaskB();"
- TaskB enters "use" block & updates AsyncLocal before hitting the first await (i.e. in the ExecContext of TaskA)
- TaskB completes & restores the AsyncLocal, but since its tail runs in its own ExecContext (that's just created by copy-on-write), it does nothing to TaskA's ExecContext
- TaskA here sees the value set by TaskB.

**Comment by alexyakunin** [comment]
I am not absolutely sure that what I wrote above should happen, but I'd check for ~ this scenario, because the likelyhood it works like this seem to be pretty high :)

**Comment by alexyakunin** [comment]
> In my (shallow) understanding, the same AsyncLocal instance won't be shared by two simultaneously executing threads, but I may be wrong.

When you set or read AsyncLocal, this operation is guaranteed to be thread-safe. But the object you put there can be shared across multiple threads.

Overall, it works _nearly_ as follows:
- AsyncLocals are stored in ExecutionContext (think it's an ImmutableDictionary)
- Once task starts, its ExecutionContext is the same object as the ExecutionContext of its parent task
- Once AsyncLocal gets written, current task's ExectionContext gets replaced with a new one.

So the problem I wrote about earlier is: as far as I remember, the `Task` object is created only ~ when the async method hits the first await (i.e. there is a real reason to create `Task` object at this point), and until this happens, there is no other choice but to use ExecutionContext from the parent task at this point.
