### ISSUE TITLE
Guard against multiple disposings

### ISSUE THREAD

**Issue by truegoodwill** [Tyrrrz/Contextual#3]
This is great Alexy!! 
Not really an issue, just a discussion.

1. Your disposable utility does not guard against multiple disposings. With the current implementation, storing `previous` in the disposable function's closure, this will not introduce a bug... yet. 

2. This code does not guard against out-of-order disposals ... this would be the biggest potential bug. You need to throw a suitable exception when user code disposes out of order.

3. It's recommended to use immutable types when storing in AsyncLocal. I like how you've just provided a base class and let the user roll their own ... do you have any thoughts about how to safeguard with immutables? https://blog.stephencleary.com/2013/04/implicit-async-context-asynclocal.html

**Comment by truegoodwill** [comment]
I think, if I were implementing this, personally, I would store an `ImmutableStack<T> where T : Context` in the `AsyncLocal`. 

The stack would be initialized with first value `new T()`

A disposal would result in popping the stack, with safeguard against multiple disposing (now required) and checks to make sure the disposals are not out of order.

I don't know how to make sure T is an immutable type though ... any ideas?

**Comment by Tyrrrz** [comment]
Hi @truegoodwill 

1. That's a good point. There should be a guard for that.
2. Also good idea. Alternatively, we could also add an analyzer that raises an error for this at build time.
3. If I understand the question correctly, I believe it should be fine. Because only the reference to the last context is tracked by `AsyncLocal` as opposed to an entire stack, pushing new context on one `AsyncLocal` will have no effect on other `AsyncLocal`s.

> I think, if I were implementing this, personally, I would store an `ImmutableStack<T> where T : Context` in the `AsyncLocal`.
> 
> The stack would be initialized with first value `new T()`
> 
> A disposal would result in popping the stack, with safeguard against multiple disposing (now required) and checks to make sure the disposals are not out of order.
> 
> I don't know how to make sure T is an immutable type though ... any ideas?

Can you come up with a minimal demo that produces an error with the current design? We can then add it as a test for future reference.

**Comment by truegoodwill** [comment]
:) I'll keep this in mind and make a PR when I get a chance. Cheerio!!

**Comment by Tyrrrz** [comment]
Added some guarding against it here: https://github.com/Tyrrrz/Contextual/blob/6944b669f4977d92fa3ce6c817714f6b569b7415/Contextual/ContextScope.cs#L34-L39

It's not bullet proof but it's the easiest solution without introducing state to the struct. And the struct is used to reduce allocations.

**Comment by truegoodwill** [comment]
Perhaps add "else throw blah blah blah". Good start! Sorry I haven't been active on this yet.

**Comment by Tyrrrz** [comment]
I think it's a general guideline to avoid exceptions in `Dispose()` as much as possible.
